/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CoupangPlusRouteImport } from './routes/coupang-plus'
import { Route as CenterRouteImport } from './routes/center'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromoBannerRouteImport } from './routes/promo-banner'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as ApiPromoUploadRouteImport } from './routes/api/promo-upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupangPlusRoute = CoupangPlusRouteImport.update({
  id: '/coupang-plus',
  path: '/coupang-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterRoute = CenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoBannerRoute = PromoBannerRouteImport.update({
  id: '/promo-banner',
  path: '/promo-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoUploadRoute = ApiPromoUploadRouteImport.update({
  id: '/api/promo-upload',
  path: '/api/promo-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/center': typeof CenterRoute
  '/coupang-plus': typeof CoupangPlusRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/apply': typeof ApiApplyRoute
  '/promo-banner': typeof PromoBannerRoute
  '/api/promo-upload': typeof ApiPromoUploadRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/center': typeof CenterRoute
  '/coupang-plus': typeof CoupangPlusRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/apply': typeof ApiApplyRoute
  '/promo-banner': typeof PromoBannerRoute
  '/api/promo-upload': typeof ApiPromoUploadRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/center': typeof CenterRoute
  '/coupang-plus': typeof CoupangPlusRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/apply': typeof ApiApplyRoute
  '/promo-banner': typeof PromoBannerRoute
  '/api/promo-upload': typeof ApiPromoUploadRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/center'
    | '/coupang-plus'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/apply'
    | '/promo-banner'
    | '/api/promo-upload'
    | '/privacy'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/center'
    | '/coupang-plus'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/apply'
    | '/promo-banner'
    | '/api/promo-upload'
    | '/privacy'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/center'
    | '/coupang-plus'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/apply'
    | '/promo-banner'
    | '/api/promo-upload'
    | '/privacy'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CenterRoute: typeof CenterRoute
  CoupangPlusRoute: typeof CoupangPlusRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiApplyRoute: typeof ApiApplyRoute
  PromoBannerRoute: typeof PromoBannerRoute
  ApiPromoUploadRoute: typeof ApiPromoUploadRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupang-plus': {
      id: '/coupang-plus'
      path: '/coupang-plus'
      fullPath: '/coupang-plus'
      preLoaderRoute: typeof CoupangPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-banner': {
      id: '/promo-banner'
      path: '/promo-banner'
      fullPath: '/promo-banner'
      preLoaderRoute: typeof PromoBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-upload': {
      id: '/api/promo-upload'
      path: '/api/promo-upload'
      fullPath: '/api/promo-upload'
      preLoaderRoute: typeof ApiPromoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CenterRoute: CenterRoute,
  CoupangPlusRoute: CoupangPlusRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiApplyRoute: ApiApplyRoute,
  PromoBannerRoute: PromoBannerRoute,
  ApiPromoUploadRoute: ApiPromoUploadRoute,
  PrivacyRoute: PrivacyRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
