/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RentRouteImport } from './routes/rent'
import { Route as PromoMetaRouteImport } from './routes/promo-meta'
import { Route as PromoBannerRouteImport } from './routes/promo-banner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MissionDataRouteImport } from './routes/mission-data'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CoupangPlusRouteImport } from './routes/coupang-plus'
import { Route as CenterRouteImport } from './routes/center'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPromoUploadRouteImport } from './routes/api/promo-upload'
import { Route as ApiPromoExtractRouteImport } from './routes/api/promo-extract'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiApplyRouteImport } from './routes/api/apply'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoMetaRoute = PromoMetaRouteImport.update({
  id: '/promo-meta',
  path: '/promo-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoBannerRoute = PromoBannerRouteImport.update({
  id: '/promo-banner',
  path: '/promo-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionDataRoute = MissionDataRouteImport.update({
  id: '/mission-data',
  path: '/mission-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupangPlusRoute = CoupangPlusRouteImport.update({
  id: '/coupang-plus',
  path: '/coupang-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterRoute = CenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoUploadRoute = ApiPromoUploadRouteImport.update({
  id: '/api/promo-upload',
  path: '/api/promo-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoExtractRoute = ApiPromoExtractRouteImport.update({
  id: '/api/promo-extract',
  path: '/api/promo-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/center': typeof CenterRoute
  '/coupang-plus': typeof CoupangPlusRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mission': typeof MissionRoute
  '/mission-data': typeof MissionDataRoute
  '/privacy': typeof PrivacyRoute
  '/promo-banner': typeof PromoBannerRoute
  '/promo-meta': typeof PromoMetaRoute
  '/rent': typeof RentRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/promo-extract': typeof ApiPromoExtractRoute
  '/api/promo-upload': typeof ApiPromoUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/center': typeof CenterRoute
  '/coupang-plus': typeof CoupangPlusRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mission': typeof MissionRoute
  '/mission-data': typeof MissionDataRoute
  '/privacy': typeof PrivacyRoute
  '/promo-banner': typeof PromoBannerRoute
  '/promo-meta': typeof PromoMetaRoute
  '/rent': typeof RentRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/promo-extract': typeof ApiPromoExtractRoute
  '/api/promo-upload': typeof ApiPromoUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/center': typeof CenterRoute
  '/coupang-plus': typeof CoupangPlusRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mission': typeof MissionRoute
  '/mission-data': typeof MissionDataRoute
  '/privacy': typeof PrivacyRoute
  '/promo-banner': typeof PromoBannerRoute
  '/promo-meta': typeof PromoMetaRoute
  '/rent': typeof RentRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/promo-extract': typeof ApiPromoExtractRoute
  '/api/promo-upload': typeof ApiPromoUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/center'
    | '/coupang-plus'
    | '/docs'
    | '/llms.txt'
    | '/mission'
    | '/mission-data'
    | '/privacy'
    | '/promo-banner'
    | '/promo-meta'
    | '/rent'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/store'
    | '/api/apply'
    | '/api/chat'
    | '/api/promo-extract'
    | '/api/promo-upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/center'
    | '/coupang-plus'
    | '/docs'
    | '/llms.txt'
    | '/mission'
    | '/mission-data'
    | '/privacy'
    | '/promo-banner'
    | '/promo-meta'
    | '/rent'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/store'
    | '/api/apply'
    | '/api/chat'
    | '/api/promo-extract'
    | '/api/promo-upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/center'
    | '/coupang-plus'
    | '/docs'
    | '/llms.txt'
    | '/mission'
    | '/mission-data'
    | '/privacy'
    | '/promo-banner'
    | '/promo-meta'
    | '/rent'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/store'
    | '/api/apply'
    | '/api/chat'
    | '/api/promo-extract'
    | '/api/promo-upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CenterRoute: typeof CenterRoute
  CoupangPlusRoute: typeof CoupangPlusRoute
  DocsRoute: typeof DocsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MissionRoute: typeof MissionRoute
  MissionDataRoute: typeof MissionDataRoute
  PrivacyRoute: typeof PrivacyRoute
  PromoBannerRoute: typeof PromoBannerRoute
  PromoMetaRoute: typeof PromoMetaRoute
  RentRoute: typeof RentRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPromoExtractRoute: typeof ApiPromoExtractRoute
  ApiPromoUploadRoute: typeof ApiPromoUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-meta': {
      id: '/promo-meta'
      path: '/promo-meta'
      fullPath: '/promo-meta'
      preLoaderRoute: typeof PromoMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-banner': {
      id: '/promo-banner'
      path: '/promo-banner'
      fullPath: '/promo-banner'
      preLoaderRoute: typeof PromoBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-data': {
      id: '/mission-data'
      path: '/mission-data'
      fullPath: '/mission-data'
      preLoaderRoute: typeof MissionDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupang-plus': {
      id: '/coupang-plus'
      path: '/coupang-plus'
      fullPath: '/coupang-plus'
      preLoaderRoute: typeof CoupangPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-upload': {
      id: '/api/promo-upload'
      path: '/api/promo-upload'
      fullPath: '/api/promo-upload'
      preLoaderRoute: typeof ApiPromoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-extract': {
      id: '/api/promo-extract'
      path: '/api/promo-extract'
      fullPath: '/api/promo-extract'
      preLoaderRoute: typeof ApiPromoExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CenterRoute: CenterRoute,
  CoupangPlusRoute: CoupangPlusRoute,
  DocsRoute: DocsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MissionRoute: MissionRoute,
  MissionDataRoute: MissionDataRoute,
  PrivacyRoute: PrivacyRoute,
  PromoBannerRoute: PromoBannerRoute,
  PromoMetaRoute: PromoMetaRoute,
  RentRoute: RentRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPromoExtractRoute: ApiPromoExtractRoute,
  ApiPromoUploadRoute: ApiPromoUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
